//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenEng.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IMDAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IMDAResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGenEng.Properties.IMDAResources", typeof(IMDAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The job is complete 的本地化字符串。
        /// </summary>
        public static string job_complete {
            get {
                return ResourceManager.GetString("job_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The job is failed 的本地化字符串。
        /// </summary>
        public static string job_failed {
            get {
                return ResourceManager.GetString("job_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The job is not exist 的本地化字符串。
        /// </summary>
        public static string job_not_exist {
            get {
                return ResourceManager.GetString("job_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The job is starting 的本地化字符串。
        /// </summary>
        public static string job_starting {
            get {
                return ResourceManager.GetString("job_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 config.xml load error 的本地化字符串。
        /// </summary>
        public static string load_error {
            get {
                return ResourceManager.GetString("load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parse config info is error 的本地化字符串。
        /// </summary>
        public static string parse_config_error {
            get {
                return ResourceManager.GetString("parse_config_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parse job info is error 的本地化字符串。
        /// </summary>
        public static string parse_job_error {
            get {
                return ResourceManager.GetString("parse_job_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parse job name for menu is error 的本地化字符串。
        /// </summary>
        public static string parse_job_menu_error {
            get {
                return ResourceManager.GetString("parse_job_menu_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 parse template info is error 的本地化字符串。
        /// </summary>
        public static string parse_template_error {
            get {
                return ResourceManager.GetString("parse_template_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The template is complete to gen 的本地化字符串。
        /// </summary>
        public static string template_complete {
            get {
                return ResourceManager.GetString("template_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The template is failed to gen 的本地化字符串。
        /// </summary>
        public static string template_failed {
            get {
                return ResourceManager.GetString("template_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The template file parse failed 的本地化字符串。
        /// </summary>
        public static string template_parse_failed {
            get {
                return ResourceManager.GetString("template_parse_failed", resourceCulture);
            }
        }
    }
}
